version: "2"
services:
  server:
    build:
      context: .
      dockerfile: ./backend/production.Dockerfile
    ports:
      - 8000:8000
    environment: {GO_ENV:""}
    volumes:
      - ./:/app

    
