version: '2'
services: 
  server:
    build:     
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
    command: go run .

  client:
    build:
        context: .
        dockerfile: ./frontend/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
    command: npm run dev